server:
  port: 8002
spring:
  application:
    name: aigou-product-dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:org/yjq/aigou/mapper/*Mapper.xml
  type-aliases-package: org.yjq.aigou.domain,org.yjq.aigou.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true