server:
  port: 9527
spring:
  application:
    name: application-zuul-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com #显示的名字
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: aigou-plat-dev #这个名字需要和消费者的名字对应 dev对应的就是dev  test对应的就是test
    plat.path: /plat/**
    product.serviceId: aigou-product-dev #这个名字需要和消费者的名字对应 dev对应的就是dev  test对应的就是test
    product.path: /product/**
    common.serviceId: aigou-common-dev #这个名字需要和消费者的名字对应 dev对应的就是dev  test对应的就是test
    common.path: /common/**
  ignored-services: "*"
  prefix: "/services"