server:
  port: 9527
spring:
  application:
    name: application-zuul-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com #显示的名字
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: aigou-plat-test
    plat.path: /plat/**
    product.serviceId: aigou-product-test
    product.path: /product/**
    common.serviceId: aigou-common-test
    common.path: /common/**
  ignored-services: "*"
  prefix: "/services"
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
